services:
  web:
    container_name: educhronia-web
    build:
      context: ./EduChronia-web
      dockerfile: Dockerfile.dev
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - ./EduChronia-web:/app
      - /app/node_modules
    environment:
      - API_BASE_URL=${API_BASE_URL}
    depends_on:
      - api
    restart: unless-stopped

  api:
    user: "${UID}:${GID}"
    container_name: educhronia-api
    build:
      context: ./EduChronia-api
      dockerfile: Dockerfile.dev
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./EduChronia-api:/app
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - HOST=${API_HOST}
      - PORT=${API_PORT}
      - DATABASE_URL=${POSTGRES_URL}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: educhronia-postgres
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  pgdata:
