services:
  web:
    container_name: educhronia-web
    build:
      context: ./EduChronia-web
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - ./EduChronia-web:/workspaces/EduChronia-web:cached
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_HOST_API_BASE_URL=${HOST_API_BASE_URL}
    command: sh -c "bun install && bun run dev"

  api:
    container_name: educhronia-api
    build:
      context: ./EduChronia-api
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./EduChronia-api:/workspaces/EduChronia-api:cached
    environment:
      - NODE_ENV=development
      - PORT=${API_PORT}
      - HOST=${API_HOST}
      - HOST_WEB_BASE_URL=${HOST_WEB_BASE_URL}
      - HOST_API_BASE_URL=${HOST_API_BASE_URL}
      - BETTER_AUTH_BASE_URL=${BETTER_AUTH_BASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "bun install && bun run dev"

  postgres:
    image: postgres:alpine
    container_name: educhronia-postgres
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  pgdata:
